/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "bologna": {
    "base": "bologna",
    "width": 3000,
    "height": 1615,
    "fallbackWidth": 1920,
    "fallbackHeight": 1034,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1920,
    "height": 1278,
    "fallbackWidth": 1920,
    "fallbackHeight": 1278,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1920,
    "height": 1524,
    "fallbackWidth": 1920,
    "fallbackHeight": 1524,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1920,
    "height": 1358,
    "fallbackWidth": 800,
    "fallbackHeight": 566,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1350,
    "height": 810,
    "fallbackWidth": 800,
    "fallbackHeight": 480,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3840,
    "height": 2229,
    "fallbackWidth": 1920,
    "fallbackHeight": 1115,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic-centre": {
    "base": "historic-centre",
    "width": 3840,
    "height": 2558,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mosaics": {
    "base": "mosaics",
    "width": 3840,
    "height": 3059,
    "fallbackWidth": 1920,
    "fallbackHeight": 1530,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 3840,
    "height": 1804,
    "fallbackWidth": 1920,
    "fallbackHeight": 902,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "porto-corsini": {
    "base": "porto-corsini",
    "width": 2400,
    "height": 1359,
    "fallbackWidth": 1920,
    "fallbackHeight": 1087,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "san-marino": {
    "base": "san-marino",
    "width": 3348,
    "height": 1842,
    "fallbackWidth": 1920,
    "fallbackHeight": 1056,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "san-vitale": {
    "base": "san-vitale",
    "width": 3840,
    "height": 3128,
    "fallbackWidth": 1920,
    "fallbackHeight": 1564,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "venice": {
    "base": "venice",
    "width": 3300,
    "height": 1512,
    "fallbackWidth": 1920,
    "fallbackHeight": 880,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 2592,
    "height": 3872,
    "fallbackWidth": 800,
    "fallbackHeight": 1195,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
